module DocumentExporter
  class Base
    def self.pdf_key: (untyped `type`) -> ("pdf" | ::String)

    @included_materials: Array[Integer]

    def initialize: (untyped document, ?::Hash[untyped, untyped] options) -> void
    def export: -> untyped
    def included_materials: (?context_type: ::Symbol) -> Array[Integer]
    def ordered_materials: (untyped material_ids) -> untyped

    private

    def base_path: (untyped name) -> untyped
    def render_template: (untyped path, layout: untyped) -> untyped
    def template_path: (untyped name) -> untyped
  end
end
